document.write( '<div class=\"player\">\n' );
document.write( '  \n' );
document.write( '            <!-- Define the section for displaying details -->\n' );
document.write( '            <div class=\"details\">\n' );
// document.write( '              <!-- <div class=\"now-playing\">PLAYING x OF y</div> -->\n' );
document.write( '              <div class=\"track-art\"></div>\n' );
// document.write( '              <div class=\"track-name\">Track Name</div>\n' );
document.write( '              <div class=\"track-artist\">Track Artist</div>\n' );
document.write( '            </div>\n' );
document.write( '          \n' );
document.write( '            <!-- Define the section for displaying track buttons -->\n' );
document.write( '            <div class=\"buttons\">\n' );
document.write( '              <div class=\"prev-track\" onclick=\"prevTrack()\">\n' );
document.write( '                <i class=\"fa fa-step-backward fa-2x\"></i>\n' );
document.write( '              </div>\n' );
document.write( '              <div class=\"playpause-track\" onclick=\"playpauseTrack()\">\n' );
document.write( '                <i class=\"fa fa-play-circle fa-5x\"></i>\n' );
document.write( '              </div>\n' );
document.write( '              <div class=\"next-track\" onclick=\"nextTrack()\">\n' );
document.write( '                <i class=\"fa fa-step-forward fa-2x\"></i>\n' );
document.write( '              </div>\n' );
document.write( '            </div>\n' );
document.write( '          \n' );
document.write( '            <!-- Define the section for displaying the seek slider-->\n' );
document.write( '            <div class=\"slider_container\">\n' );
document.write( '              <div class=\"current-time\">00:00</div>\n' );
document.write( '              <input type=\"range\" min=\"1\" max=\"100\"\n' );
document.write( '                value=\"0\" class=\"seek_slider\" onchange=\"seekTo()\">\n' );
document.write( '              <div class=\"total-duration\">00:00</div>\n' );
document.write( '            </div>\n' );
document.write( '          \n' );
document.write( '            <!-- Define the section for displaying the volume slider-->\n' );
document.write( '            <div class=\"slider_container\">\n' );
document.write( '              <i class=\"fa fa-volume-down\"></i>\n' );
document.write( '              <input type=\"range\" min=\"1\" max=\"100\"\n' );
document.write( '                value=\"99\" class=\"volume_slider\" onchange=\"setVolume()\">\n' );
document.write( '              <i class=\"fa fa-volume-up\"></i>\n' );
document.write( '            </div>\n' );
document.write( '          </div>' );
